// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGZ1ANY3ELPEuPXyoT2yNb2INIaDX4R6M',
    appId: '1:480269377105:web:0ac2e6a0259d101b3c6270',
    messagingSenderId: '480269377105',
    projectId: 'drivener-wt31ga',
    authDomain: 'drivener-wt31ga.firebaseapp.com',
    storageBucket: 'drivener-wt31ga.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0PodArUHidQqJhr1QrCnf_AUYfzSqQ8M',
    appId: '1:480269377105:android:5619a3203ba5f62f3c6270',
    messagingSenderId: '480269377105',
    projectId: 'drivener-wt31ga',
    storageBucket: 'drivener-wt31ga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0gYPGlhRh7eJtYwfJR-CCFaxvMEiZhlA',
    appId: '1:480269377105:ios:74940b128bc418c63c6270',
    messagingSenderId: '480269377105',
    projectId: 'drivener-wt31ga',
    storageBucket: 'drivener-wt31ga.firebasestorage.app',
    iosBundleId: 'com.example.drivenerFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0gYPGlhRh7eJtYwfJR-CCFaxvMEiZhlA',
    appId: '1:480269377105:ios:74940b128bc418c63c6270',
    messagingSenderId: '480269377105',
    projectId: 'drivener-wt31ga',
    storageBucket: 'drivener-wt31ga.firebasestorage.app',
    iosBundleId: 'com.example.drivenerFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGZ1ANY3ELPEuPXyoT2yNb2INIaDX4R6M',
    appId: '1:480269377105:web:cae6faf8dfb09eb93c6270',
    messagingSenderId: '480269377105',
    projectId: 'drivener-wt31ga',
    authDomain: 'drivener-wt31ga.firebaseapp.com',
    storageBucket: 'drivener-wt31ga.firebasestorage.app',
  );
}
